---
# Minimal galaxy.yml for a playbook project for tools to recognize this as a collection

namespace: "caixa_collection"
name: "caixa_project"
readme: README.md
version: 0.0.1
authors:
  - your name <example@domain.com>

description: Collection for caixa_collection.caixa_project playbook project
license: ["GPL-3.0-or-later"]
# TO-DO: update the tags based on your content type
tags: ["tools"]
repository: NA
